name: ci

on:
  pull_request:
    paths:
      - Dockerfile
      - requirements.txt

jobs:
  borg_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.borg_version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - name: Get borg version
        id: borg_version
        run: |
          VERSION=$(python -c "from pkg_resources import parse_requirements; print(next(filter(lambda r: r.name == 'borgbackup', parse_requirements(open('requirements.txt').read()))).specs[0][1])")
          echo $VERSION
          echo "name=version::${VERSION}" >> $GITHUB_OUTPUT

  build_image:
    runs-on: ubuntu-latest
    needs: borg_version
    env:
      PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ env.PLATFORMS }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: ${{ env.PLATFORMS }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          push: false
          build-args: |
            VERSION=${{ needs.borg_version.outputs.version }}
          platforms: ${{ env.PLATFORMS }}
          cache-from: type=gha
